// Generates supabase/migrations/20260929000003_content.sql from the TS source of truth.
// Run: node --experimental-strip-types scripts/gen-content-sql.mts
import { writeFileSync } from "node:fs";
import { CURRICULA, slugify } from "../src/lib/content/curricula.ts";
import { ACHIEVEMENTS } from "../src/lib/content/achievements.ts";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const out: string[] = [
  "-- GENERATED by scripts/gen-content-sql.mts. Reference data needed in every environment.",
  "",
  "insert into public.admin_emails (email) values ('ardennescorporate@gmail.com') on conflict do nothing;",
  "",
];

out.push("insert into public.achievements (id, title, description, icon, beta_only, sort) values");
out.push(
  ACHIEVEMENTS.map((a, i) => `  (${q(a.id)}, ${q(a.title)}, ${q(a.description)}, ${q(a.icon)}, ${"betaOnly" in a ? "true" : "false"}, ${i + 1})`).join(",\n") +
    "\non conflict (id) do update set title = excluded.title, description = excluded.description, icon = excluded.icon, beta_only = excluded.beta_only, sort = excluded.sort;",
);
out.push("");

CURRICULA.forEach((c, ci) => {
  const cslug = slugify(c.subject);
  out.push(`-- ${c.subject}`);
  out.push(
    `insert into public.courses (subject, slug, system, year_level, sort) values (${q(c.subject)}, ${q(cslug)}, ${q(c.system)}, ${q(c.yearLevel)}, ${ci}) on conflict (subject) do nothing;`,
  );
  let seq = 0;
  c.units.forEach((un, ui) => {
    out.push(
      `insert into public.units (course_id, position, title, description) select id, ${ui}, ${q(un.title)}, ${q(un.description)} from public.courses where subject = ${q(c.subject)} on conflict do nothing;`,
    );
    un.lessons.forEach((l, li) => {
      out.push(
        `insert into public.lessons (unit_id, course_id, position, seq, title, slug) select u.id, c.id, ${li}, ${seq}, ${q(l)}, ${q(slugify(l))} from public.units u join public.courses c on c.id = u.course_id where c.subject = ${q(c.subject)} and u.position = ${ui} on conflict do nothing;`,
      );
      seq++;
    });
  });
  out.push("");
});

writeFileSync(new URL("../supabase/migrations/20260929000003_content.sql", import.meta.url), out.join("\n"));
console.log("wrote content migration");
